set(GAME_FILES
        src/game/board/audio.c
        src/game/board/basic_space.c
        src/game/board/battle.c
        src/game/board/block.c
        src/game/board/boo.c
        src/game/board/boo_house.c
        src/game/board/bowser.c
        src/game/board/char_wheel.c
        src/game/board/com.c
        src/game/board/com_path.c
        src/game/board/fortune.c
        src/game/board/item.c
        src/game/board/last5.c
        src/game/board/lottery.c
        src/game/board/main.c
        src/game/board/mg_setup.c
        src/game/board/model.c
        src/game/board/mushroom.c
        src/game/board/pause.c
        src/game/board/player.c
        src/game/board/roll.c
        src/game/board/shop.c
        src/game/board/space.c
        src/game/board/star.c
        src/game/board/start.c
        src/game/board/tutorial.c
        src/game/board/ui.c
        src/game/board/view.c
        src/game/board/warp.c
        src/game/board/window.c

        src/game/armem.c
        src/game/card.c
        src/game/chrman.c
        src/game/ClusterExec.c
        src/game/data.c
        src/game/decode.c
        src/game/dvd.c
        src/game/EnvelopeExec.c
        src/game/esprite.c
        src/game/fault.c
        src/game/flag.c
        src/game/font.c
        src/game/frand.c
        src/game/gamework.c
        src/game/hsfanim.c
        src/game/hsfdraw.c
        src/game/hsfex.c
        src/game/hsfload.c
        src/game/hsfman.c
        src/game/hsfmotion.c
        src/game/init.c
        src/game/main.c
        src/game/malloc.c
        src/game/mapspace.c
        src/game/memory.c
        src/game/messdata.c
        src/game/minigame_seq.c
        src/game/objdll.c
        src/game/objmain.c
        src/game/objsub.c
        src/game/objsysobj.c
        src/game/ovllist.c
        src/game/pad.c
        src/game/perf.c
        src/game/printfunc.c
        src/game/process.c
        src/game/saveload.c
        src/game/ShapeExec.c
        src/game/sprman.c
        src/game/sprput.c
        src/game/window.c
        src/game/wipe.c

        src/libhu/setvf.c
        src/libhu/subvf.c
)

set(PORT_FILES
        src/port/achievements.cpp
        src/port/audio.c
        src/port/byteswap.cpp
        src/port/config.cpp
        src/port/dolassets.cpp
        #        src/port/dvd.c
        src/port/file_select.cpp
        src/port/file_select.hpp
        src/port/imgui.cpp
        src/port/io.cpp
        src/port/iso_validate.cpp
        src/port/OS.c
        src/port/portmain.cpp
        src/port/settings.cpp
        src/port/stubs.c

        src/port/ui/achievements.cpp
        src/port/ui/achievements.hpp
        src/port/ui/bool_button.cpp
        src/port/ui/bool_button.hpp
        src/port/ui/button.cpp
        src/port/ui/button.hpp
        src/port/ui/component.cpp
        src/port/ui/component.hpp
        src/port/ui/controller_config.cpp
        src/port/ui/controller_config.hpp
        src/port/ui/document.cpp
        src/port/ui/document.hpp
        src/port/ui/event.cpp
        src/port/ui/event.hpp
        src/port/ui/graphics_tuner.cpp
        src/port/ui/graphics_tuner.hpp
        src/port/ui/input.cpp
        src/port/ui/input.hpp
        src/port/ui/modal.cpp
        src/port/ui/modal.hpp
        src/port/ui/nav_types.hpp
        src/port/ui/number_button.cpp
        src/port/ui/number_button.hpp
        src/port/ui/overlay.cpp
        src/port/ui/overlay.hpp
        src/port/ui/pane.cpp
        src/port/ui/pane.hpp
        src/port/ui/menu_bar.cpp
        src/port/ui/menu_bar.hpp
        src/port/ui/prelaunch.cpp
        src/port/ui/prelaunch.hpp
        src/port/ui/preset.cpp
        src/port/ui/preset.hpp
        src/port/ui/select_button.cpp
        src/port/ui/select_button.hpp
        src/port/ui/settings.cpp
        src/port/ui/settings.hpp
        src/port/ui/compat.cpp
        src/port/ui/string_button.cpp
        src/port/ui/string_button.hpp
        src/port/ui/tab_bar.cpp
        src/port/ui/tab_bar.hpp
        src/port/ui/ui.cpp
        src/port/ui/ui.hpp
        src/port/ui/window.cpp
        src/port/ui/window.hpp
)
